theme: jekyll-theme-slate
title: Dr.-Ing. Félix Leaman W.
description: "Departamento de Ingeniería Mecánica, Universidad de Concepción \n Oficina 340, Piso 3, Edificio Central Facultad de Ingeniería \n Contacto fleaman@udec.cl"
