theme: jekyll-theme-slate
title: Dr.-Ing. Félix Leaman W.
description: 
    afiliacion: Departamento Ingeniería Mecánica, Universidad de Concepción
    oficina: Oficina 340, Edificio Central Facultad de Ingeniería
